version: '2.1'

services:
  cutting:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/cookies/cutting
    ports:
      - $SERVER_PORT:$SERVER_PORT
